name: calculator_app
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  fonts:
    - family: GoudyBookletter
      fonts:
        - asset: fonts/GoudyBookletter1911-Regular.ttf

    - family: LibreBaskerville
      fonts:
        - asset: fonts/LibreBaskerville-Regular.ttf
        - asset: fonts/LibreBaskerville-Italic.ttf
        - asset: fonts/LibreBaskerville-Bold.ttf






  uses-material-design: true

